Added : spooling conversions, stream formats and system callback and mimetype support using libmagic

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3767,6 +3767,36 @@ else $as_nop
 fi
 
 
+if $PKGCONFIG --exists libmagic; then
+    # Add the necessary compiler and linker flags
+    CFLAGS="$CFLAGS $($PKGCONFIG --cflags libmagic)"
+    LIBS="$LIBS $($PKGCONFIG --libs libmagic)"
+else
+    # If libmagic is not found, exit with an error
+    echo "libmagic is required for gutenprint-printer-app." >&2
+    exit 1
+fi
+
+if $PKGCONFIG --exists libcupsfilters; then
+    # Add the necessary compiler and linker flags
+    CFLAGS="$CFLAGS $($PKGCONFIG --cflags libcupsfilters)"
+    LIBS="$LIBS $($PKGCONFIG --libs libcupsfilters)"
+else
+    # If libmagic is not found, exit with an error
+    echo "libcupsfilters is required for gutenprint-printer-app." >&2
+    exit 1
+fi
+
+if $PKGCONFIG --exists libppd; then
+    # Add the necessary compiler and linker flags
+    CFLAGS="$CFLAGS $($PKGCONFIG --cflags libppd)"
+    LIBS="$LIBS $($PKGCONFIG --libs libppd)"
+else
+    # If libmagic is not found, exit with an error
+    echo "libppd is required for gutenprint-printer-app." >&2
+    exit 1
+fi
+
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}cups-config", so it can be a program name with args.
 set dummy ${ac_tool_prefix}cups-config; ac_word=$2
